### PR TITLE
slot基础上支持 slot-scope

### PR DESCRIPTION
**Pull request by songlairui**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

实现关键点：
 slot-scope 生成到slot.wxml 中： scopedSlots目前一个 slot[name] 仅支持一个子组件。收集到时，将之与slots合并
 slot-scope 作用参数： 操作ast，后处理，将自定义别名全部替换成约定的 $scopedata。在 template[data] 中拼接 slotscope参数
 v-for 下使用slot-scope :模板，js文件中render函数进行同步改造。遇到 slot-scope后，使用形如 `$root[$kk + '0v1'], $root[$kk + '0v2']` 的变量

### CODE REVIEW

**Comment by songlairui** [comment]
有些bug，重新优化了下逻辑。整理一下重新提交

**Comment by yz-xlame** [comment]
想问一下，为什么只支持一个子组件呢？子组件嵌套slot怎么办呢

**Comment by songlairui** [comment]
> 想问一下，为什么只支持一个子组件呢？子组件嵌套slot怎么办呢

我描述的不清楚。我本意是说 
```vue
<div>
  <slot name='a'></slot>
  <slot name='a'></slot>
</div>
```

```vue
<div>
  <div slot='a'></slot>
  <div slot='a'></slot>
</div>
```

是这样，具名的插槽不能写多个。只能用1个。
这可能是vue2.4的限制

**Comment by yz-xlame** [comment]
@songlairui 含有slot的组件是否可以直接传值给slot呢？如：
<TemplateA>
    <slot :key="value"></slot>
<TemplateA>
我尝试了一下，貌似不行，无法传递过去

**Pull request closed without merging**
