### PR TITLE
fix: 组件的生命周期响应问题

### PR DESCRIPTION
**Pull request by zysndy**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
1. 修改`mpType`为`component`时，组件的`ready`响应由`onReady`改为`ready`，对应微信官方组件的生命周期
2. 增加组件的生命周期钩子`attached`，`ready`，`moved`，`detached`

### CODE REVIEW

**Comment by anchengjian** [comment]
补充一下 component-lifestyle 相关的测试到 [test/mp/runtime](https://github.com/Meituan-Dianping/mpvue/tree/master/test/mp/runtime) 吧

**Comment by zysndy** [comment]
@anchengjian  👌

**Comment by zysndy** [comment]
@anchengjian 大佬测试用例加上了，麻烦看一下是否有问题～

**Comment by Yeecz** [comment]
问一下组件生命周期这个在哪个版本可以使用？

**Comment by anchengjian** [comment]
最新的版本就可以用，有啥问题么？

**Comment by F-loat** [comment]
这个 pr 解决的场景是什么？ready、attached 这些生命周期只有小程序的 [自定义组件](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/lifetimes.html) 才有，但是目前 mpvue 组件是用 template 实现的，所以不会有 ready 等事件，只有页面的 onReady，而小程序原生的自定义组件应该不经过 mpvue 处理吧

**Pull request merged**
