### PR TITLE
fix: raw component props

### PR DESCRIPTION
**Pull request by thundernet8**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

将mpvue写的vue组件转换为小程序原生组件并给原生小程序引用，发现无法传递props，查询发现normalizeProperties方法取vue中定义的props时取的properties，但是如果我还是用vue习惯的props来定义属性的话实际运行时发现vue vm实例上提供的是props，就取不到值了

#320

### CODE REVIEW

**Comment by thundernet8** [comment]
测试可以使用这个[脚手架](https://github.com/thundernet8/generator-mpvue-rc)

**Comment by anchengjian** [comment]
发现你的代码不能跑过 `npm run test:mpvue` ，就不 revert 了， 直接调整了一下 normalizeProperties 方法，https://github.com/Meituan-Dianping/mpvue/commit/ddf65415e3c74673a608c1aebdccd43391583afe 还请再测试一下。
最后，感谢PR。

**Pull request merged**
